version: '3.8'
services:
  postgresql:
    image: postgres:alpine
    container_name: postgresql
    env_file:
      - .env
    volumes:
      - ./db_data/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 1s
      timeout: 1s
      retries: 5
  telegrambot:
    build: .
    container_name: telegrambot
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/telegrambot/
